server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-exception: true
    include-binding-errors: always

spring:
  application:
    name: websocket-group-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/websocket_group_demo
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

jwt:
  secret-key: ajrcollection-server-jwt-token-key
  expiration-time: 604800000
